package compiler

import (
	"s8/src/ast"
	"s8/src/code"
	"s8/src/object"
)

type Compiler struct {
	instructions code.Instructions // Hold generated bytecode
	constants    []object.Object   // A slice that is our the constant pool
}

type Bytecode struct {
	Instructions code.Instructions
	Constants    []object.Object // The constant pool
}

func New() *Compiler {
	return &Compiler{
		instructions: code.Instructions{},
		constants:    []object.Object{},
	}
}

func (c *Compiler) Compile(node ast.Node) error {
	return nil
}

// Return compiled bytecode
func (c *Compiler) Bytecode() *Bytecode {
	return &Bytecode{
		Instructions: c.instructions,
		Constants:    c.constants,
	}
}
